- name: my_play
  hosts: all
  tasks:

  - name: regsiter_myresult
    apt:
      name: nginx
      register: my_result


  - name: debug
    debug:
     var: my_result
    when: my_result.changed == true or my_result.failed != true