
- name: My first play
  hosts: all
  vars_files:
    - ./my_vars.yml
  tasks:

  - name: update_cache
    tags: update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install nginx
    tags: install
    apt:
      name: "{{package}}"
      state: "{{version}}"

  - name: Start service nginx
    tags: always
    ansible.builtin.sysvinit:
      name: "{{package}}"
      state: "{{state}}"
  