- name: My first play
  hosts: all
  tasks:

  - name: update_cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install nginx
    ansible.builtin.apt:
      name: "{{item}}"  
      state: present
    loop:
    - nginx
    - mariadb-server
    - curl